language: python
python:
  - '2.7'
  - '3.4'
  - '3.5'
  - '3.6'
install:
  - python setup.py install
script:
  - 'coverage run --source=jam --rcfile=jam/tests/coverage.rc setup.py test'
  - 'coverage report -m --rcfile=jam/tests/coverage.rc'  
after_success: 'coveralls'
